import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "fs";

const isProd = process.argv[2] === "production";

const commonOptions = {
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: "main.js",
  sourcemap: !isProd,
  minify: isProd,
  format: "cjs", // Obsidian plugins are loaded as CommonJS
  target: ["es2018"],
  platform: "browser",
  external: [
    "obsidian",
    "electron",
    "@codemirror/*",
    "@lezer/*",
    "codemirror",
  ],
  plugins: [
    sveltePlugin({
      preprocess: sveltePreprocess(),
      compilerOptions: {
        dev: !isProd,
        css: "external", // Output CSS to external file
      },
    }),
  ],
};

async function build() {
  if (isProd) {
    await esbuild.build(commonOptions);
  } else {
    const ctx = await esbuild.context(commonOptions);
    await ctx.watch();
    // Keep process alive while watching
    // eslint-disable-next-line no-console
    console.log("Watching for changes...");
  }

  // Combine src/styles.css with Svelte-generated main.css into styles.css for Obsidian
  let combinedCss = "";

  // Add manual styles from src/styles.css
  if (existsSync("src/styles.css")) {
    combinedCss += readFileSync("src/styles.css", "utf8") + "\n";
  }

  // Add Svelte component styles from main.css (generated by esbuild-svelte)
  if (existsSync("main.css")) {
    combinedCss += readFileSync("main.css", "utf8");
  }

  // Write combined styles to styles.css (which Obsidian loads)
  if (combinedCss) {
    writeFileSync("styles.css", combinedCss);
  }
}

build().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
